fixed actions workflow with new docker compose

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,7 +15,7 @@ jobs:
 
     - name: Stop and Remove Existing Container
       run: |
-        docker-compose down || true  # Stops and removes existing containers, but doesn’t fail if they don't exist
+        docker compose down || true  # Stops and removes existing containers, but doesn’t fail if they don't exist
 
     - name: Remove Unused Images
       run: |
@@ -23,4 +23,4 @@ jobs:
 
     - name: Deploy Application
       run: |
-        docker-compose up -d --build
+        docker compose up -d --build
